// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Screen2

#ifndef _SCREEN2_UI_H
#define _SCREEN2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
void ui_event_Arc1( lv_event_t * e);
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_795822493);   // assets\LOGO-KMUTNB--300x300.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
